package com.example.administrator.demo_zkl01.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.demo_zkl01.startfragmentpage.homepage.bean.DaoSearch;

import com.example.administrator.demo_zkl01.dao.DaoSearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoSearchDaoConfig;

    private final DaoSearchDao daoSearchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoSearchDaoConfig = daoConfigMap.get(DaoSearchDao.class).clone();
        daoSearchDaoConfig.initIdentityScope(type);

        daoSearchDao = new DaoSearchDao(daoSearchDaoConfig, this);

        registerDao(DaoSearch.class, daoSearchDao);
    }
    
    public void clear() {
        daoSearchDaoConfig.clearIdentityScope();
    }

    public DaoSearchDao getDaoSearchDao() {
        return daoSearchDao;
    }

}
